import Link from "next/link";
import Image from "next/image";
import type { ReactNode } from "react";

export function PageHeader({ eyebrow, title, lede, link }: { eyebrow: string; title: string; lede?: string; link?: { href: string; label: string } }) { return <header className={`sectionHead ${link ? "headRow" : ""}`}><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2>{lede && <p className="lede">{lede}</p>}</div>{link && <Link className="linkArrow" href={link.href}>{link.label} <span>→</span></Link>}</header>; }
export function Card({ title, children, number }: { title: string; children: ReactNode; number?: string }) { return <article className="card">{number && <span className="number">{number}</span>}<span className="icon" aria-hidden="true"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7"><path d="M3 12h4l2.5-7 4 14L16 12h5" /></svg></span><h3>{title}</h3><p>{children}</p></article>; }
export function ServiceRow({ number, title, children, tags, imagePosition = "center", imageSrc = "/hero-network.png" }: { number: number; title: string; children: ReactNode; tags?: string[]; imagePosition?: string; imageSrc?: string }) { return <li className="service"><span>{String(number).padStart(2,"0")}</span><div className="serviceCopy"><h3>{title}</h3><p>{children}</p>{tags && <div className="tags">{tags.map(t=><i key={t}>{t}</i>)}</div>}</div><div className="serviceImage"><Image src={imageSrc} alt="" fill sizes="(max-width: 660px) 100vw, 260px" style={{ objectFit: "cover", objectPosition: imagePosition }} /></div></li>; }
export function Step({ number, title, children }: { number: number; title: string; children: ReactNode }) { return <li className="step"><span>{String(number).padStart(2,"0")}</span><h3>{title}</h3><p>{children}</p></li>; }
export function Phase({ number, label, title, children, items }: { number: number; label: string; title: string; children: ReactNode; items?: string[] }) { return <article className="phase"><div><b>{String(number).padStart(2,"0")}</b><span>{label}</span></div><div><h2>{title}</h2><p>{children}</p>{items && <ul>{items.map(item=><li key={item}>{item}</li>)}</ul>}</div></article>; }
export function FAQ({ items }: { items: { q: string; a: string }[] }) { return <div className="faq">{items.map(({q,a})=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div>; }
export function CTA({ title, description }: { title: string; description: string }) { return <section className="cta"><div className="wrap ctaInner"><div><p className="eyebrow">Start with a survey</p><h2>{title}</h2><p>{description}</p></div><Link className="btn invert" href="/contact">Request a survey <span>→</span></Link></div></section>; }
