import { CTA, PageHeader, Phase, ServiceRow } from "@/components/marketing";
const services = [
  ["wireless","Wireless range extension and infrastructure","Precision RF signal mapping and high-density access points installed during early construction for seamless roaming.",["RF heat mapping","Access point design","High-density Wi-Fi"]],
  ["cabling","Network optimisation and structured cabling","Structured Cat6 and Cat6A drops, fibre backbones, server racks and VLANs that clear bottlenecks.",["Cat6A & fibre","Rack builds","VLAN design"]],
  ["firewall","Next generation firewalls and security","Hardware firewalls with deep packet inspection, automated threat mitigation and isolated guest networks.",["Policy design","Segmentation","Threat filtering"]],
  ["managed","Managed network support","Continuous monitoring, firmware updates and responsive helpdesk support.",["Monitoring","Patching","Incident response"]],
  ["vpn","Secure remote access and VPN","Point-to-site and site-to-site VPNs with Zero Trust MFA for remote teams and satellite offices.",["Zero Trust","MFA","Site-to-site VPN"]],
] as const;
export default function Services() { const images = ["/service-wireless.png", "/service-cabling.png", "/service-firewall.png", "/hero-network.png", "/hero-network.png"]; return <><PageHeaderBlock eyebrow="Services" title="Everything between the rack and the endpoint." lede="Five disciplines, one team. We can own a build from first drawing to handover, or step into an existing facility and fix what is failing." /><section className="section"><div className="wrap"><ol className="services">{services.map(([id,title,body,tags],i)=><div id={id} key={id}><ServiceRow number={i+1} title={title} tags={[...tags]} imageSrc={images[i]} imagePosition={["right center","center center","right bottom","left center","center bottom"][i]}>{body}</ServiceRow></div>)}</ol></div></section><section className="section alt"><div className="wrap"><PageHeader eyebrow="Engagement models" title="Three ways to work with us." /><div className="phases"><Phase number={1} label="Build" title="New build" items={["Blueprint review", "Structured cabling", "Commissioning"]}>We work alongside your build team while access is easy and changes are inexpensive.</Phase><Phase number={2} label="Repair" title="Retrofit and remediation" items={["Audit", "Remediation plan", "Performance tuning"]}>We diagnose the weak points in an existing facility and give you a practical route back to reliable service.</Phase><Phase number={3} label="Operate" title="Ongoing management" items={["24/7 monitoring", "Patch maintenance", "Clear reporting"]}>Keep the network in the hands of people who know how it was built.</Phase></div></div></section><CTA title="Not sure which one you need?" description="Describe the building and the problem. We will recommend a sensible first step." /></> }
function PageHeaderBlock(p:{eyebrow:string;title:string;lede:string}) { return <section className="pageHead"><div className="wrap"><p className="crumbs">Home <span>/</span> {p.eyebrow}</p><PageHeader {...p} /></div></section>; }
